apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress  
  template:
    metadata:
      labels:
        app: wordpress   
    spec:
      containers:
      - image: wordpress:6.4-php8.1-apache
        name: wordpress
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: WORDPRESS_DB_HOST
          value: db-service
        - name: WORDPRESS_DB_USER
          value: wordpress

---

apiVersion: v1
kind: Service
metadata:
  name: wp-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
  selector:
    app: wordpress
